/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DIRECT_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "Trpc": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}